upd flakes

diff --git a/.github/workflows/CI.yaml b/.github/workflows/CI.yaml
--- a/.github/workflows/CI.yaml
+++ b/.github/workflows/CI.yaml
@@ -8,70 +8,69 @@ jobs:
       - name: Install Nix
         uses: cachix/install-nix-action@v22
         with:
-          extra_nix_config: "access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}\nsubstituters = https://cache.nixos.org/ https://cache.iog.io https://nix-community.cachix.org https://deemp.cachix.org \ntrusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= deemp.cachix.org-1:9shDxyR2ANqEPQEEYDL/xIOnoPwxHot21L5fiZnFL18=\nstore = ${{ matrix.store }}\nkeep-outputs = true\nkeep-derivations = true\n"
+          extra_nix_config: |
+            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
+            substituters = https://cache.nixos.org/ https://nix-community.cachix.org https://cache.iog.io https://deemp.cachix.org
+            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= deemp.cachix.org-1:9shDxyR2ANqEPQEEYDL/xIOnoPwxHot21L5fiZnFL18=
+            keep-outputs = true
+            keep-derivations = true
           install_url: https://releases.nixos.org/nix/nix-2.16.1/install
       - name: Restore and cache Nix store
-        uses: actions/cache@v3.3.0
+        uses: deemp/cache-nix-too@v1
         with:
-          key: ${{ runner.os }}-nix-${{ hashfiles('**/flake.nix', '**/flake.lock') }}-cachix
-          path: ${{ matrix.store }}
+          key: nix-${{ matrix.os }}-cachix-${{ hashfiles('**/flake.nix', '**/flake.lock') }}
           restore-keys: |
-            ${{ runner.os }}-nix-${{ hashfiles('**/flake.nix', '**/flake.lock') }}-cachix
-            ${{ runner.os }}-nix-
-      - if: matrix.os == 'ubuntu-20.04'
+            nix-${{ matrix.os }}-cachix-${{ hashfiles('**/flake.nix', '**/flake.lock') }}
+            nix-${{ matrix.os }}-cachix-
+      - if: matrix.os == 'ubuntu-22.04'
         name: Config git for github-actions
         run: |
           git config user.name github-actions
           git config user.email github-actions@github.com
-      - if: matrix.os == 'ubuntu-20.04'
+      - if: matrix.os == 'ubuntu-22.04'
+        name: Format Nix files
+        run: |+
+          nix run nix-dev/#format
+
+      - if: matrix.os == 'ubuntu-22.04'
         name: Update flake locks
         run: |+
-          git pull --rebase --autostash
-
-          nix build nix-dev/#updateLocks
           nix run nix-dev/#updateLocks
 
-      - if: matrix.os == 'ubuntu-20.04'
+      - if: matrix.os == 'ubuntu-22.04'
         name: Convert README.hs to README.md
         run: |+
-          nix build nix-dev/#writeREADME
           nix run nix-dev/#writeREADME
 
-      - if: matrix.os == 'ubuntu-20.04'
+      - if: matrix.os == 'ubuntu-22.04'
         name: Commit changes
-        run: |
-          git commit -a -m "action: Update flake locks" \
-            -m "action: Convert README.hs to README.md" && git push || echo ""
-      - name: Build lima
+        run: |+
+          git commit -a -m "action: Format" \
+            -m "action: Update flake locks" \
+            -m "action: Convert README.hs to README.md" \
+                                 && git push || echo "push failed!"
+
+      - if: matrix.os == 'ubuntu-22.04'
+        name: Build lima
         run: |+
           nix build .#
 
           nix build .#sdist
 
-      - name: Log in to Cachix
-        run: |
-          nix build nixpkgs#cachix
-          nix run nixpkgs#cachix -- authtoken ${{ secrets.CACHIX_AUTH_TOKEN }}
       - env:
+          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
           CACHIX_CACHE: ${{ secrets.CACHIX_CACHE }}
         name: Push flakes to Cachix
         run: |+
-          nix build nix-dev/#pushToCachix
           nix run nix-dev/#pushToCachix
 
-      - name: Collect garbage in /nix/store
-        run: nix store gc
     strategy:
       matrix:
-        include:
-          - os: macos-11
-            store: auto
-          - os: macos-12
-            store: auto
-          - os: ubuntu-20.04
-            store: /home/runner/nix
-          - os: ubuntu-22.04
-            store: /home/runner/nix
+        os:
+          - macos-11
+          - macos-12
+          - ubuntu-20.04
+          - ubuntu-22.04
 name: Nix CI
 "on":
   pull_request: {}
