upd workflow

diff --git a/.github/workflows/CI.yaml b/.github/workflows/CI.yaml
--- a/.github/workflows/CI.yaml
+++ b/.github/workflows/CI.yaml
@@ -19,17 +19,17 @@ jobs:
       - name: Restore and cache Nix store
         uses: nix-community/cache-nix-action@v1
         with:
-          key: nix-${{ matrix.os }}-ci-${{ hashfiles('**/flake.nix', '**/flake.lock') }}
+          key: nix-${{ matrix.os }}-job-${{ hashfiles('**/flake.nix', '**/flake.lock') }}
           linux-gc-enabled: true
           linux-max-store-size: 5100000000
           macos-gc-enabled: true
           macos-max-store-size: 5100000000
           restore-keys: |
-            nix-${{ matrix.os }}-ci-
+            nix-${{ matrix.os }}-job-
       - name: Remove old cache profiles
         run: rm -rf /nix/var/nix/profiles/cache
       - if: matrix.os == 'ubuntu-22.04'
-        name: Config git for github-actions
+        name: Configure git for github-actions
         run: |
           git config --global user.name github-actions
           git config --global user.email github-actions@github.com
@@ -44,6 +44,16 @@ jobs:
           nix profile install nix-dev/#updateLocks
           nix run nix-dev/#updateLocks
       - if: matrix.os == 'ubuntu-22.04'
+        name: Commit & Push
+        run: |-
+          git add .
+          git commit \
+            -m "action" \
+            -m "Format Nix files" \
+            -m "Update flake locks" \
+            || echo "commit failed!"
+          git push
+      - if: matrix.os == 'ubuntu-22.04'
         name: Convert README.hs to README.md
         run: |-
           nix profile install nix-dev/#writeDocs
@@ -53,19 +63,16 @@ jobs:
         run: |-
           git add .
           git commit \
-            -m "action: Format Nix files" \
-            -m "action: Update flake locks" \
-            -m "action: Convert README.hs to README.md" \
+            -m "action" \
+            -m "Format Nix files" \
+            -m "Update flake locks" \
+            -m "Convert README.hs to README.md" \
             || echo "commit failed!"
           git push
       - name: Build lima
         run: |
           nix profile install .#
-          nix profile install .#sdist --priority 1
-      - name: Save flakes
-        run: |-
-          nix profile install nix-dev/#saveFlakes
-          nix run nix-dev/#saveFlakes
+          nix profile install .#sdist
       - env:
           CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
           CACHIX_CACHE: ${{ secrets.CACHIX_CACHE }}
